import type { Metadata } from "next";
import { Suspense } from "react";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ThemePixelTransition from "@/components/ThemePixelTransition";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";
import ScrollAnimations from "@/components/ScrollAnimations";
import LoadingScreen from "@/components/LoadingScreen";
import { LoadingProvider } from "@/contexts/LoadingContext";
import MainContentWrapper from "@/components/MainContentWrapper";
import GlobalAiChat from "@/components/GlobalAiChat";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ThemeProvider langsung di sini */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <LoadingProvider>
            <ThemePixelTransition />
            {/* Smooth scroll + GSAP scroll animations — purely behavioral */}
            <SmoothScrollProvider />
            <ScrollAnimations />
            <Suspense fallback={null}>
              <LoadingScreen />
            </Suspense>
            <MainContentWrapper>
              {children}
            </MainContentWrapper>
            <GlobalAiChat />
          </LoadingProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
